// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.2
// source: tictactoe.proto

package tictactoe

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MoveRequest *MoveRequest `protobuf:"bytes,1,opt,name=moveRequest,proto3" json:"moveRequest,omitempty"`
}

func (x *PlayStreamRequest) Reset() {
	*x = PlayStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tictactoe_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayStreamRequest) ProtoMessage() {}

func (x *PlayStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tictactoe_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayStreamRequest.ProtoReflect.Descriptor instead.
func (*PlayStreamRequest) Descriptor() ([]byte, []int) {
	return file_tictactoe_proto_rawDescGZIP(), []int{0}
}

func (x *PlayStreamRequest) GetMoveRequest() *MoveRequest {
	if x != nil {
		return x.MoveRequest
	}
	return nil
}

type PlayStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId   string      `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	BoardState *BoardState `protobuf:"bytes,2,opt,name=boardState,proto3" json:"boardState,omitempty"`
}

func (x *PlayStreamResponse) Reset() {
	*x = PlayStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tictactoe_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayStreamResponse) ProtoMessage() {}

func (x *PlayStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tictactoe_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayStreamResponse.ProtoReflect.Descriptor instead.
func (*PlayStreamResponse) Descriptor() ([]byte, []int) {
	return file_tictactoe_proto_rawDescGZIP(), []int{1}
}

func (x *PlayStreamResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PlayStreamResponse) GetBoardState() *BoardState {
	if x != nil {
		return x.BoardState
	}
	return nil
}

type MoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Row      int32  `protobuf:"varint,2,opt,name=row,proto3" json:"row,omitempty"`
	Column   int32  `protobuf:"varint,3,opt,name=column,proto3" json:"column,omitempty"`
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tictactoe_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tictactoe_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_tictactoe_proto_rawDescGZIP(), []int{2}
}

func (x *MoveRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *MoveRequest) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *MoveRequest) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

type BoardState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message  string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Board    []string `protobuf:"bytes,3,rep,name=board,proto3" json:"board,omitempty"`
	GameOver bool     `protobuf:"varint,4,opt,name=gameOver,proto3" json:"gameOver,omitempty"`
}

func (x *BoardState) Reset() {
	*x = BoardState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tictactoe_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoardState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardState) ProtoMessage() {}

func (x *BoardState) ProtoReflect() protoreflect.Message {
	mi := &file_tictactoe_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardState.ProtoReflect.Descriptor instead.
func (*BoardState) Descriptor() ([]byte, []int) {
	return file_tictactoe_proto_rawDescGZIP(), []int{3}
}

func (x *BoardState) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BoardState) GetBoard() []string {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *BoardState) GetGameOver() bool {
	if x != nil {
		return x.GameOver
	}
	return false
}

var File_tictactoe_proto protoreflect.FileDescriptor

var file_tictactoe_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x74, 0x69, 0x63, 0x74, 0x61, 0x63, 0x74, 0x6f, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x74, 0x69, 0x63, 0x74, 0x61, 0x63, 0x74, 0x6f, 0x65, 0x22, 0x4d, 0x0a, 0x11,
	0x50, 0x6c, 0x61, 0x79, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x38, 0x0a, 0x0b, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x69, 0x63, 0x74, 0x61, 0x63, 0x74,
	0x6f, 0x65, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b,
	0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x67, 0x0a, 0x12, 0x50,
	0x6c, 0x61, 0x79, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x35, 0x0a,
	0x0a, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x74, 0x69, 0x63, 0x74, 0x61, 0x63, 0x74, 0x6f, 0x65, 0x2e, 0x42, 0x6f,
	0x61, 0x72, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0a, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x22, 0x53, 0x0a, 0x0b, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x6f,
	0x77, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x22, 0x58, 0x0a, 0x0a, 0x42, 0x6f, 0x61,
	0x72, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4f,
	0x76, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4f,
	0x76, 0x65, 0x72, 0x32, 0x63, 0x0a, 0x10, 0x54, 0x69, 0x63, 0x54, 0x61, 0x63, 0x54, 0x6f, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x1c, 0x2e, 0x74, 0x69, 0x63, 0x74, 0x61, 0x63, 0x74, 0x6f,
	0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x74, 0x69, 0x63, 0x74, 0x61, 0x63, 0x74, 0x6f, 0x65, 0x2e,
	0x50, 0x6c, 0x61, 0x79, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x79, 0x78, 0x78, 0x33, 0x35, 0x34, 0x32,
	0x2f, 0x74, 0x69, 0x63, 0x74, 0x61, 0x63, 0x74, 0x6f, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_tictactoe_proto_rawDescOnce sync.Once
	file_tictactoe_proto_rawDescData = file_tictactoe_proto_rawDesc
)

func file_tictactoe_proto_rawDescGZIP() []byte {
	file_tictactoe_proto_rawDescOnce.Do(func() {
		file_tictactoe_proto_rawDescData = protoimpl.X.CompressGZIP(file_tictactoe_proto_rawDescData)
	})
	return file_tictactoe_proto_rawDescData
}

var file_tictactoe_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tictactoe_proto_goTypes = []interface{}{
	(*PlayStreamRequest)(nil),  // 0: tictactoe.PlayStreamRequest
	(*PlayStreamResponse)(nil), // 1: tictactoe.PlayStreamResponse
	(*MoveRequest)(nil),        // 2: tictactoe.MoveRequest
	(*BoardState)(nil),         // 3: tictactoe.BoardState
}
var file_tictactoe_proto_depIdxs = []int32{
	2, // 0: tictactoe.PlayStreamRequest.moveRequest:type_name -> tictactoe.MoveRequest
	3, // 1: tictactoe.PlayStreamResponse.boardState:type_name -> tictactoe.BoardState
	0, // 2: tictactoe.TicTacToeService.PlayStream:input_type -> tictactoe.PlayStreamRequest
	1, // 3: tictactoe.TicTacToeService.PlayStream:output_type -> tictactoe.PlayStreamResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tictactoe_proto_init() }
func file_tictactoe_proto_init() {
	if File_tictactoe_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tictactoe_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tictactoe_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tictactoe_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tictactoe_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoardState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tictactoe_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tictactoe_proto_goTypes,
		DependencyIndexes: file_tictactoe_proto_depIdxs,
		MessageInfos:      file_tictactoe_proto_msgTypes,
	}.Build()
	File_tictactoe_proto = out.File
	file_tictactoe_proto_rawDesc = nil
	file_tictactoe_proto_goTypes = nil
	file_tictactoe_proto_depIdxs = nil
}
